config/routes.rb
MlclspApp::Application.routes.draw do

  resources :resource_periods

  resources :periods

  resources :follower_products

  resources :followers
  resources :resources
  resources :products
  resources :problem_solutions
  resources :demands
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  root :to => 'pages#home'

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match 'problem_solutions/optimize', :to => 'problem_solutions#optimize'
  match 'problem_solutions/read_production_inventory_quantities', :to => 'problem_solutions#read_production_inventory_quantities'
  match 'problem_solutions/read_and_show_ofv', :to => 'problem_solutions#read_and_show_ofv'
  match 'problem_solutions/show_production_quantities', :to => 'problem_solutions#show_production_quantities'
  match 'problem_solutions/show_inventory_quantities', :to => 'problem_solutions#show_inventory_quantities'
  match 'problem_solutions/delete_production_quantities', :to => 'problem_solutions#delete_production_quantities'
  match '/about', :to => 'pages#about'
end

app/models/problem_solution.rb
class ProblemSolution < ActiveRecord::Base
end

app/controllers/problem_solutions_controller.rb
class ProblemSolutionsController < ApplicationController

  def index
    @title = "Data Input & Solution"
  end



def optimize

    if File.exist?("MLCLSP_Input_Instanz1.inc")
      File.delete("MLCLSP_Input_Instanz1.inc")
    end
    f=File.new("MLCLSP_Input_Instanz1.inc", "w")           #"w" für write
    printf(f, "Set k / \n")
    @products = Product.find(:all)
    @products.each { |so| printf(f, "k" + so.id.to_s + "\n") }
    printf(f, "/" + "\n\n")

    printf(f, "t / \n")
    @periods = Period.find(:all)
    @periods.each { |si| printf(f, "t" + si.id.to_s + "\n") }
    printf(f, "/" + "\n\n")

    printf(f, "j / \n")
    @resources = Resource.find(:all)
    @resources.each { |li| printf(f, "j" + li.id.to_s + "\n") }
    printf(f, "/;" + "\n\n")

    printf(f, "alias(k,i); \n")

    printf(f, "Set NF(k,i);\n")
    printf(f, "NF(k,i) = no;\n")
    @follower_products = FollowerProduct.find(:all)
    @follower_products.each do |nf|
      printf(f, "NF( 'k" + nf.follower_id.to_s + "', 'k" + nf.product_id.to_s + "') = yes;\n")
    end

    printf(f, "Set PR(k,j);\n")
    printf(f, "PR(k,j) = no;\n")
    @products.each do |pr|
      printf(f, "PR( 'k" + pr.id.to_s + "', 'j" + pr.resource.to_s + "') = yes;\n")
    end

    printf(f, "\n\n")

    printf(f, "Parameters\n  h(k) /\n")
    @products.each { |so| printf(f, "k" + so.id.to_s + "  " + so.storage_cost.to_s + "\n") }
    printf(f, "/" + "\n\n")

    printf(f, "\n s(k) /\n")
    @products.each { |si| printf(f, "k" + si.id.to_s + "  " + si.setup_cost.to_s + "\n") }
    printf(f, "/" + "\n\n")

    printf(f, "\n tb(k) /\n")
    @products.each { |li| printf(f, "k" + li.id.to_s + "  " + li.working_time.to_s + "\n") }
    printf(f, "/" + "\n\n")

    printf(f, "\n tr(k) /\n")
    @products.each { |li| printf(f, "k" + li.id.to_s + "  " + li.setup_time.to_s + "\n") }
    printf(f, "/" + "\n\n")

    printf(f, "\n z(k) /\n")
    @products.each { |li| printf(f, "k" + li.id.to_s + "  " + li.leadtime_shift.to_s + "\n") }
    printf(f, "/" + "\n\n")

    printf(f, "\n y0(k) /\n")
    @products.each { |li| printf(f, "k" + li.id.to_s + "  " + li.start_inventory.to_s + "\n") }
    printf(f, "/" + "\n\n")

    printf(f, "\n")

    printf(f, "a(k,i) /\n")
    @follower_products.each { |li|
    printf(f, "k" + li.product_id.to_s + ".k" + li.follower_id.to_s + " " + li.coefficient.to_s + "\n")}
    printf(f, "/" + "\n\n")

    printf(f, "b(j,t) /\n")
    @resource_periods = ResourcePeriod.find(:all)
    @resource_periods.each { |li|
    printf(f, "j" + li.resource_id.to_s + ".t" + li.period_id.to_s + " " + li.capacity.to_s + "\n")}
    printf(f, "/" + "\n\n")

    printf(f, "d(k,t) /\n")
    @demands = Demand.find(:all)
    @demands.each { |li|
    printf(f, "k" + li.product_id.to_s + ".t" + li.period_id.to_s + " " + li.demand_quantity.to_s + "\n")}
    printf(f, "/;" + "\n\n")

    printf(f, "Scalar M; \n")
    printf(f, "M = 100000; \n")

    f.close


    #if File.exist?("mlclsp_solution.txt")                # hier steht Lsg drin
    #  File.delete("mlclsp_solution.txt")
    #end


    system "gams mlclsp"      # GAMS-Einbindung

    #@transport_links = TransportLink.find(:all)
    render :template => "problem_solutions/index"

    end

    def read_production_inventory_quantities

    @problemsolution=ProblemSolution.all
    @problemsolution.each {|problemsolution|
    problemsolution.destroy}

    fi=File.open("mlclsp_solution1.txt", "r")
    fi.each { |line| # printf(f,line)
      sa=line.split(";")
      sa0=sa[0].delete "k "
      sa1=sa[1].delete "t "
      sa2=sa[2].delete " "

      @problem_solution=ProblemSolution.new
      @problem_solution.product_name=sa0
      @problem_solution.period_name=sa1
      @problem_solution.production_quantity=sa2
      @problem_solution.save
    }

   fi.close

    @inventorysolution=InventorySolution.all
    @inventorysolution.each {|problemsolution|
    problemsolution.destroy}

    fi=File.open("mlclsp_solution2.txt", "r")
    fi.each { |line| # printf(f,line)
      sa=line.split(";")
      sa0=sa[0].delete "k "
      sa1=sa[1].delete "t "
      sa2=sa[2].delete " "

      @inventory_solution=InventorySolution.new
      @inventory_solution.product_name=sa0
      @inventory_solution.period_name=sa1
      @inventory_solution.inventory=sa2
      @inventory_solution.save
    }

   fi.close

    #@transport_links = TransportLink.find(:all)
    render :template => "problem_solutions/index"

    end




  def delete_production_quantities
   @problem_solutions = ProblemSolution.all
   @problem_solutions.each { |li|
   li.production_quantity=0.0
   li.save
   }

   @inventory_solutions = InventorySolution.all
   @inventory_solutions.each { |li|
   li.inventory=0.0
   li.save
   }

   render :template => "problem_solutions/index"
  end

   def read_and_show_ofv
     if File.exist?("ofv.txt")
       fi=File.open("ofv.txt", "r")
       line=fi.readline
       fi.close
       sa=line.split(" ")
       @objective_function_value=sa[1]
     else
       @objective_function_value=nil
     end

      #@problem_solution = ProblemSolution.find(:all)
     render :template => "problem_solutions/index"
   end




end

app/helpers/problem_solutions_helper.rb
module ProblemSolutionsHelper

  def objective_function_value_response
    if @objective_function_value.nil?
      return "No objective value is available!"
    else
      return "objective value is "+@objective_function_value + "!"
    end
  end



end

app/views/problem_solutions/index.html.erb
<h1>Data Input & Solution for the MLCLSP Model</h1>

<li><%= link_to "Here", resources_path %> you can type in the resources.</li>
<li><%= link_to "Here", products_path %> you can type in the products features.</li>
<li><%= link_to "Here", followers_path %> you can type in the followers.</li>
<li><%= link_to "Here", follower_products_path %> you can type in the dependencies.</li>
<li><%= link_to "Here", periods_path %> you can type in the necessary periods.</li>
<li><%= link_to "Here", demands_path %> you can type in the demands.</li>
<li><%= link_to "Here", resource_periods_path %> you can type in the resource capacity.</li>

<br />

<%= objective_function_value_response %>



<%= button_to "Optimize", :controller => 'problem_solutions', :action =>  'optimize'  %>
<%= button_to "Import objective value", :controller => 'problem_solutions', :action => 'read_and_show_ofv' %>
<%= button_to "Import production - and inventory quantities", :controller => 'problem_solutions', :action =>  'read_production_inventory_quantities'  %>
<%= button_to "Show production quantities", :controller => 'problem_solutions', :action =>  'show_production_quantities'  %>
<%= button_to "Show inventory quantities", :controller => 'problem_solutions', :action =>  'show_inventory_quantities'  %>
<%= button_to "Delete", :controller => 'problem_solutions', :action => 'delete_production_quantities' %>

app/views/problem_solutions/show_inventory_quantities.html.erb
<h1>Showing the results</h1>
<%= @title= "Result Inventory Quantity" %>
<table>
  <tr>
    <th>product name</th>
    <th>period name</th>
    <th>inventory quantity</th>
    <th></th>
  </tr>

<% InventorySolution.all.each do |ps| %>
  <tr>
    <td><%= ps.product_name %></td>
    <td><%= ps.period_name %></td>
    <td><%= ps.inventory %></td>

  </tr>
<% end %>
</table>

app/views/problem_solutions/show_production_quantities.html.erb
<h1>Showing the results</h1>
<%= @title= "Result Production Quantity" %>
<table>
  <tr>
    <th>product name</th>
    <th>period name</th>
    <th>production quantity</th>
    <th></th>
  </tr>

<% ProblemSolution.all.each do |ps| %>
  <tr>
    <td><%= ps.product_name %></td>
    <td><%= ps.period_name %></td>
    <td><%= ps.production_quantity %></td>

  </tr>
<% end %>
</table>