config/routes.rb
MlclspApp::Application.routes.draw do

  resources :resource_periods

  resources :periods

  resources :follower_products

  resources :followers
  resources :resources
  resources :products
  resources :problem_solutions
  resources :demands
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  root :to => 'pages#home'

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match 'problem_solutions/optimize', :to => 'problem_solutions#optimize'
  match 'problem_solutions/read_production_inventory_quantities', :to => 'problem_solutions#read_production_inventory_quantities'
  match 'problem_solutions/read_and_show_ofv', :to => 'problem_solutions#read_and_show_ofv'
  match 'problem_solutions/show_production_quantities', :to => 'problem_solutions#show_production_quantities'
  match 'problem_solutions/show_inventory_quantities', :to => 'problem_solutions#show_inventory_quantities'
  match 'problem_solutions/delete_production_quantities', :to => 'problem_solutions#delete_production_quantities'
  match '/about', :to => 'pages#about'
end

app/models/demand.rb
class Demand < ActiveRecord::Base
  belongs_to :product, :class_name => "Product"
  belongs_to :period, :class_name => "Period"

  attr_accessible :product_id, :period_id, :demand_quantity

  validates :product_id, :presence => true,
                   :length => { :maximum => 5 }

  validates :period_id, :presence => true,
                   :length => { :maximum => 5 }

  validates :demand_quantity, :presence => true,
                   :length => { :maximum => 10 },
                   :numericality => { :only_integer => true}

end

app/controllers/demands_controller.rb
class DemandsController < ApplicationController
  # GET /demands
  # GET /demands.json
  def index
    @title= "Listing Demands"
    @demands = Demand.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @demands }
    end
  end

  # GET /demands/1
  # GET /demands/1.json
  def show
    @title= "Show Demands"
    @demand = Demand.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @demand }
    end
  end

  # GET /demands/new
  # GET /demands/new.json
  def new
    @title= "New Demands"
    @demand = Demand.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @demand }
    end
  end

  # GET /demands/1/edit
  def edit
    @title= "Edit Demands"
    @demand = Demand.find(params[:id])
  end

  # POST /demands
  # POST /demands.json
  def create
    @demand = Demand.new(params[:demand])

    respond_to do |format|
      if @demand.save
        format.html { redirect_to @demand, notice: 'Demand was successfully created.' }
        format.json { render json: @demand, status: :created, location: @demand }
      else
        format.html { render action: "new" }
        format.json { render json: @demand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /demands/1
  # PUT /demands/1.json
  def update
    @demand = Demand.find(params[:id])

    respond_to do |format|
      if @demand.update_attributes(params[:demand])
        format.html { redirect_to @demand, notice: 'Demand was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @demand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /demands/1
  # DELETE /demands/1.json
  def destroy
    @demand = Demand.find(params[:id])
    @demand.destroy

    respond_to do |format|
      format.html { redirect_to demands_url }
      format.json { head :ok }
    end
  end
end

app/helpers/demands_helper.rb
module DemandsHelper
end

app/views/demands/_form.html.erb
<%= form_for(@demand) do |f| %>
  <% if @demand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@demand.errors.count, "error") %> prohibited this demand from being saved:</h2>

      <ul>
      <% @demand.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.collection_select :product_id, Product.find(:all), :id, :product_name %>
  </div>
  <div class="field">
    <%= f.label :period_id %><br />
    <%= f.collection_select :period_id, Period.find(:all), :id, :period_name %>
  </div>
  <div class="field">
    <%= f.label :demand_quantity %><br />
    <%= f.text_field :demand_quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/demands/edit.html.erb
<h1>Editing demand</h1>

<%= render 'form' %>

<%= link_to 'Show', @demand %> |
<%= link_to 'Back', demands_path %>

app/views/demands/index.html.erb
<h1>Listing demands</h1>

<table>
  <tr>
    <th>product name</th>
    <th>period name</th>
    <th>demand quantity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @demands.each do |demand| %>
  <tr>
    <td><%= demand.product.product_name %></td>
    <td><%= demand.period.period_name %></td>
    <td><%= demand.demand_quantity %></td>
    <td><%= link_to 'Show', demand %></td>
    <td><%= link_to 'Edit', edit_demand_path(demand) %></td>
    <td><%= link_to 'Destroy', demand, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Demand', new_demand_path %> |
<%= link_to 'Data Input', problem_solutions_path %>

app/views/demands/new.html.erb
<h1>New demand</h1>

<%= render 'form' %>

<%= link_to 'Back', demands_path %>

app/views/demands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>product name:</b>
  <%= @demand.product_id %>
</p>

<p>
  <b>period name:</b>
  <%= @demand.period_id %>
</p>

<p>
  <b>demand quantity:</b>
  <%= @demand.demand_quantity %>
</p>


<%= link_to 'Edit', edit_demand_path(@demand) %> |
<%= link_to 'Back', demands_path %>