config/routes.rb
MlclspApp::Application.routes.draw do

  resources :resource_periods

  resources :periods

  resources :follower_products

  resources :followers
  resources :resources
  resources :products
  resources :problem_solutions
  resources :demands
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  root :to => 'pages#home'

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match 'problem_solutions/optimize', :to => 'problem_solutions#optimize'
  match 'problem_solutions/read_production_inventory_quantities', :to => 'problem_solutions#read_production_inventory_quantities'
  match 'problem_solutions/read_and_show_ofv', :to => 'problem_solutions#read_and_show_ofv'
  match 'problem_solutions/show_production_quantities', :to => 'problem_solutions#show_production_quantities'
  match 'problem_solutions/show_inventory_quantities', :to => 'problem_solutions#show_inventory_quantities'
  match 'problem_solutions/delete_production_quantities', :to => 'problem_solutions#delete_production_quantities'
  match '/about', :to => 'pages#about'
end

app/models/follower_product.rb
class FollowerProduct < ActiveRecord::Base
  belongs_to :follower, :class_name => "Follower"
  belongs_to :product, :class_name => "Product"

  attr_accessible :coefficient, :follower_id, :product_id

  validates :coefficient, :presence => true,
                   :length => { :maximum => 5 },
                   :numericality => { :only_integer => true}

  validates :follower_id, :presence => true,
                   :length => { :maximum => 5 }

  validates :product_id, :presence => true,
                   :length => { :maximum => 5 }
end

app/controllers/follower_products_controller.rb
class FollowerProductsController < ApplicationController
  # GET /follower_products
  # GET /follower_products.json
  def index
    @title= "Listing Products Followers"
    @follower_products = FollowerProduct.all

    respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @follower_products }
    end
  end

  # GET /follower_products/1
  # GET /follower_products/1.json
  def show
    @title= "Show Products Followers"
    @follower_product = FollowerProduct.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json  { render :json => @follower_product }
    end
  end

  # GET /follower_products/new
  # GET /follower_products/new.json
  def new
    @title= "New Products Followers"
    @follower_product = FollowerProduct.new

    respond_to do |format|
      format.html # new.html.erb
      format.json  { render :json => @follower_product }
    end
  end

  # GET /follower_products/1/edit
  def edit
    @title= "Edit Products Followers"
    @follower_product = FollowerProduct.find(params[:id])
  end

  # POST /follower_products
  # POST /follower_products.json
  def create
    @follower_product = FollowerProduct.new(params[:follower_product])

    respond_to do |format|
      if @follower_product.save
        format.html { redirect_to(@follower_product, :notice => 'Follower product was successfully created.') }
        format.json  { render :json => @follower_product, :status => :created, :location => @follower_product }
      else
        format.html { render :action => "new" }
        format.json  { render :json => @follower_product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /follower_products/1
  # PUT /follower_products/1.json
  def update
    @follower_product = FollowerProduct.find(params[:id])

    respond_to do |format|
      if @follower_product.update_attributes(params[:follower_product])
        format.html { redirect_to(@follower_product, :notice => 'Follower product was successfully updated.') }
        format.json  { head :ok }
      else
        format.html { render :action => "edit" }
        format.json  { render :json => @follower_product.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /follower_products/1
  # DELETE /follower_products/1.json
  def destroy
    @follower_product = FollowerProduct.find(params[:id])
    @follower_product.destroy

    respond_to do |format|
      format.html { redirect_to(follower_products_url) }
      format.json  { head :ok }
    end
  end
end

app/helpers/follower_products_helper.rb
module FollowerProductsHelper
end

app/views/follower_products/_form.html.erb
<%= form_for(@follower_product) do |f| %>
  <% if @follower_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@follower_product.errors.count, "error") %> prohibited this follower_product from being saved:</h2>

      <ul>
      <% @follower_product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
     <%= f.label :product_id %><br />
     <%= f.collection_select :product_id, Product.find(:all), :id, :product_name %>
  </div>
   <div class="field">
    <%= f.label :follower_id %><br />
    <%= f.collection_select :follower_id, Follower.find(:all), :id, :follower_name %>
  </div>
  <div class="field">
    <%= f.label :coefficient %><br />
    <%= f.text_field :coefficient %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/follower_products/edit.html.erb
<h1>Editing follower_product</h1>

<%= render 'form' %>

<%= link_to 'Show', @follower_product %> |
<%= link_to 'Back', follower_products_path %>

app/views/follower_products/index.html.erb
<h1>Listing follower_products</h1>

<table>
  <tr>
    <th>product name</th>
    <th>follower name</th>
    <th>coefficient</th>
    <th></th>
  </tr>

<% @follower_products.each do |follower_product| %>
  <tr>
    <td><%= follower_product.product.product_name %></td>
    <td><%= follower_product.follower.follower_name %></td>
    <td><%= follower_product.coefficient %></td>
    <td><%= link_to 'Show', follower_product %></td>
    <td><%= link_to 'Edit', edit_follower_product_path(follower_product) %></td>
    <td><%= link_to 'Destroy', follower_product, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Follower product', new_follower_product_path %> |
<%= link_to 'Data Input', problem_solutions_path %>

app/views/follower_products/new.html.erb
<h1>New follower_product</h1>

<%= render 'form' %>

<%= link_to 'Back', follower_products_path %>

app/views/follower_products/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>product name:</b>
  <%= @follower_product.follower_id %>
</p>
<p>
  <b>follower name:</b>
  <%= @follower_product.product_id %>
</p>
<p>
  <b>Coefficient:</b>
  <%= @follower_product.coefficient %>
</p>


<%= link_to 'Edit', edit_follower_product_path(@follower_product) %> |
<%= link_to 'Back', follower_products_path %>