config/routes.rb
MlclspApp::Application.routes.draw do

  resources :resource_periods

  resources :periods

  resources :follower_products

  resources :followers
  resources :resources
  resources :products
  resources :problem_solutions
  resources :demands
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  root :to => 'pages#home'

  match '/signup', :to => 'users#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match 'problem_solutions/optimize', :to => 'problem_solutions#optimize'
  match 'problem_solutions/read_production_inventory_quantities', :to => 'problem_solutions#read_production_inventory_quantities'
  match 'problem_solutions/read_and_show_ofv', :to => 'problem_solutions#read_and_show_ofv'
  match 'problem_solutions/show_production_quantities', :to => 'problem_solutions#show_production_quantities'
  match 'problem_solutions/show_inventory_quantities', :to => 'problem_solutions#show_inventory_quantities'
  match 'problem_solutions/delete_production_quantities', :to => 'problem_solutions#delete_production_quantities'
  match '/about', :to => 'pages#about'
end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :resource_name %><br />
    <%= f.text_field :resource_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<h1>Listing resources</h1>

<table>
  <tr>
    <th>resource name</th>
    <th></th>
    <th></th>
  </tr>

<% @resources.each do |resource| %>
  <tr>
    <td><%= resource.resource_name %></td>
    <td><%= link_to 'Show', resource %></td>
    <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
    <td><%= link_to 'Destroy', resource, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Resource', new_resource_path %> |
<%= link_to 'Data Input', problem_solutions_path %>

app/views/resources/new.html.erb
<h1>New resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>resource name:</b>
  <%= @resource.resource_name %>
</p>




<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>